import assert from 'node:assert/strict';
import { loadTs } from './load-ts.mjs';
const load = name => loadTs(new URL(`../src/lib/${name}.ts`, import.meta.url));
const { cardCycle, prepareCardTransaction, buildCardInvoices, accountBalance, dayKey } = load('cards');
const { buildCashFlowForecast } = load('finance-forecast');
const { budgetProgress } = load('budgets');
const { buildReminders, parseReminderSettings, defaultReminderSettings } = load('reminders');
const { parseBackup, BACKUP_COLLECTIONS } = load('backup');
const { belongsToMonth } = load('finance-engine');
const { buildTransactions } = load('transactions');
const date = (year, month, day) => new Date(year, month - 1, day, 12);
const bank = { id: 'bank', userId: 'user', name: 'Banco', type: 'ContaCorrente', initialBalance: 1000 };
const card = { ...bank, id: 'card', name: 'Cartão', type: 'CartaoCredito', initialBalance: 0, limit: 2000, closingDay: 20, dueDay: 5 };
const row = { id: 'purchase', userId: 'user', description: 'Compra', value: -100, date: date(2026, 9, 20).toISOString(), accountId: 'card', categoryId: 'food', type: 'expense', status: 'PENDING' };
assert.deepEqual(cardCycle(card, row.date), { invoiceMonth: '2026-09', invoiceClosingDate: '2026-09-20', invoiceDueDate: '2026-10-05' });
assert.equal(cardCycle(card, date(2026, 9, 21)).invoiceDueDate, '2026-11-05');
assert.equal(cardCycle({ ...card, closingDay: 31, dueDay: 5 }, date(2028, 2, 29)).invoiceClosingDate, '2028-02-29');
assert.equal(cardCycle({ ...card, closingDay: 30, dueDay: 31 }, date(2027, 2, 28)).invoiceDueDate, '2027-03-31');
assert.throws(() => cardCycle({ ...card, closingDay: 0 }, row.date));
assert.throws(() => prepareCardTransaction({ ...row, type: 'income', value: 100 }, card));
const start = date(2027, 1, 31);
let nextId = 0;
const parcels = buildTransactions({ description: 'Parcelado', value: '100', date: start, accountId: 'card', categoryId: 'food', type: 'expense', status: 'PAID', frequency: 'installment', installments: '3', updateScope: 'all' }, 'user', () => `p${++nextId}`)
  .map(row => prepareCardTransaction(row, { ...card, closingDay: 30 }, start.toISOString()));
assert.deepEqual(parcels.map(row => row.invoiceMonth), ['2027-02', '2027-03', '2027-04'], 'month-end installments never collapse into one invoice');
assert.deepEqual(parcels.map(row => row.value), [-33.34, -33.33, -33.33]);
assert.ok(parcels.every(row => row.status === 'PENDING'));
const legacyParcels = parcels.map(({ invoiceMonth, invoiceClosingDate, invoiceDueDate, ...row }) => row);
assert.deepEqual(buildCardInvoices([{ ...card, closingDay: 30 }], legacyParcels).map(invoice => invoice.month), ['2027-02', '2027-03', '2027-04']);
const changedCycle = prepareCardTransaction({ ...row, id: 'changed-cycle' }, { ...card, closingDay: 25 });
assert.equal(buildCardInvoices([card], [prepareCardTransaction(row, card), changedCycle]).length, 2, 'changing closing dates preserves distinct saved cycles');
const purchase = prepareCardTransaction(row, card);
assert.equal(buildCardInvoices([card], [purchase], date(2026, 9, 20))[0].state, 'open');
assert.equal(buildCardInvoices([card], [purchase], date(2026, 9, 21))[0].state, 'closed');
assert.equal(buildCardInvoices([card], [purchase], date(2026, 10, 6))[0].state, 'late');
const paid = { ...purchase, status: 'PAID', paidFromAccountId: 'bank', paidAt: date(2026, 10, 3).toISOString() };
assert.equal(buildCardInvoices([card], [paid], date(2026, 10, 3))[0].state, 'paid');
assert.equal(accountBalance(bank, [paid], date(2026, 10, 3)), 900);
assert.equal(accountBalance(bank, [paid], date(2026, 10, 2)), 1000);
const forecast = buildCashFlowForecast([bank, card], [purchase], date(2026, 10, 3), 7);
assert.equal(forecast.startingBalance, 1000);
assert.equal(forecast.points.length, 8);
assert.equal(forecast.points.find(point => dayKey(point.date) === '2026-10-04').balance, 1000);
assert.equal(forecast.points.find(point => dayKey(point.date) === '2026-10-05').balance, 900);
const afterPayment = buildCashFlowForecast([bank, card], [paid], date(2026, 10, 3), 7);
assert.equal(afterPayment.startingBalance, 900);
assert.equal(afterPayment.endingBalance, 900);
assert.equal(afterPayment.totalOutflows, 0, 'settling the card never creates a second outflow');
const expense = { ...row, accountId: 'bank', date: date(2026, 10, 4).toISOString(), value: -1200 };
const income = { ...expense, id: 'salary', type: 'income', value: 1200, date: date(2026, 10, 6).toISOString() };
const dip = buildCashFlowForecast([bank], [expense, income], date(2026, 10, 3), 7);
assert.equal(dip.lowestBalance, -200, 'daily calculation catches shortfall hidden by weekly net');
assert.equal(dayKey(dip.lowestDate), '2026-10-04');
assert.equal(dip.endingBalance, 1000);
assert.throws(() => buildCashFlowForecast([bank], [], date(2026, 10, 3), 0));
const budget = { id: 'budget', userId: 'user', month: '2026-10', limit: 1000, categoryId: 'food' };
assert.deepEqual(budgetProgress(budget, [expense, income, { ...expense, id: 'other', categoryId: 'other' }]), { spent: 1200, remaining: -200, percent: 120 });
const categories = [{ id: 'food', userId: 'user', name: 'Alimentação', type: 'expense', color: '#112233' }];
const reminders = buildReminders([bank, card], [purchase], [], categories, defaultReminderSettings, date(2026, 10, 3));
assert.equal(reminders.length, 1);
assert.ok(reminders[0].id.startsWith('invoice:'), 'one invoice reminder instead of one per purchase');
assert.equal(buildReminders([bank, card], [paid], [], categories, defaultReminderSettings, date(2026, 10, 3)).length, 0);
assert.equal(buildReminders([bank], [expense], [budget], categories, { ...defaultReminderSettings, enabled: false }).length, 0);
const alerts = buildReminders([bank], [expense], [budget], categories, defaultReminderSettings, date(2026, 10, 3));
assert.ok(alerts.some(item => item.id === 'budget:budget' && item.urgent));
assert.deepEqual(parseReminderSettings({ daysAhead: 999, budgetPercent: -1, enabled: 'yes' }), defaultReminderSettings);
const backup = { ...Object.fromEntries(BACKUP_COLLECTIONS.map(name => [name, []])), accounts: [bank, card], categories, budgets: [budget], transactions: [paid] };
assert.deepEqual(parseBackup(backup), backup, 'backup retains all invoice/payment/category budget metadata');
assert.throws(() => parseBackup({ ...backup, accounts: [card] }));
assert.throws(() => parseBackup({ ...backup, transactions: [{ ...paid, paidAt: undefined }] }));
assert.throws(() => parseBackup({ ...backup, transactions: [{ ...paid, invoiceDueDate: '2026-02-30' }] }));
assert.throws(() => parseBackup({ ...backup, budgets: [{ ...budget, categoryId: 'missing' }] }));
const oldTimezone = process.env.TZ;
for (const timezone of ['UTC', 'America/Sao_Paulo', 'Pacific/Kiritimati']) {
  process.env.TZ = timezone;
  const cycle = cardCycle(card, date(2026, 9, 20));
  assert.equal(cycle.invoiceDueDate, '2026-10-05');
  assert.equal(belongsToMonth('2026-10-01', date(2026, 10, 3)), true);
  assert.equal(dayKey(cycle.invoiceDueDate), '2026-10-05');
  const march = buildCashFlowForecast([bank], [], date(2026, 3, 1), 15);
  assert.equal(new Set(march.points.map(point => dayKey(point.date))).size, 16);
}
if (oldTimezone === undefined) delete process.env.TZ; else process.env.TZ = oldTimezone;
console.log('Product regressions passed: invoice cycles, leap/month ends, installment cents, settlement cash, daily shortfall, budgets, reminders, backup and timezones.');
